name: ar_flutter_plugin
description: Flutter Plugin for creating (collaborative) Augmented Reality experiences - Supports ARKit for iOS and ARCore for Android devices.
version: 0.7.3
homepage: https://lars.carius.io
repository: https://github.com/CariusLars/ar_flutter_plugin

environment:
  sdk: ">=2.16.1 <3.0.0"
  #flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: 10.1.0
  vector_math: 2.1.1
  json_annotation: 4.5.0
  geolocator: 9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: io.carius.lars.ar_flutter_plugin
        pluginClass: ArFlutterPlugin
      ios:
        pluginClass: ArFlutterPlugin
